# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sake < Formula
  desc "sake is a CLI tool that enables you to run commands on servers via ssh"
  homepage "https://sakecli.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/sake/releases/download/v0.1.1/sake_0.1.1_darwin_amd64.tar.gz"
      sha256 "9430d829bc2166a1aa6976323a3c776e54cb69ad9643b06be932d42053009e43"

      def install
        bin.install "sake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alajmo/sake/releases/download/v0.1.1/sake_0.1.1_darwin_arm64.tar.gz"
      sha256 "61767a0f1014d55a3173e72178165bbe345376dbeebcda9ccc17e244f3428265"

      def install
        bin.install "sake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/sake/releases/download/v0.1.1/sake_0.1.1_linux_amd64.tar.gz"
      sha256 "24b4c5c093978faed2a17121098c8a39924bb36c48fe3e385b04b689920677b7"

      def install
        bin.install "sake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alajmo/sake/releases/download/v0.1.1/sake_0.1.1_linux_arm64.tar.gz"
      sha256 "74e5a48b552257032b71e2b4f3f077a088b25645a414f1a67d5698706b1694b5"

      def install
        bin.install "sake"
      end
    end
  end
end
