# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sake < Formula
  desc "sake is a CLI tool that enables you to run commands on servers via ssh"
  homepage "https://sakecli.com"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/sake/releases/download/v0.11.0/sake_0.11.0_darwin_amd64.tar.gz"
      sha256 "9e37afa2592b70f19d07bef3008ad16cfa529d23b9b373626a08e4fb2891e0c7"

      def install
        bin.install "sake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alajmo/sake/releases/download/v0.11.0/sake_0.11.0_darwin_arm64.tar.gz"
      sha256 "a330543a71164a5f685c4ed195251a4a8b17da48f5c18da53656106e20f0e1d6"

      def install
        bin.install "sake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alajmo/sake/releases/download/v0.11.0/sake_0.11.0_linux_arm64.tar.gz"
      sha256 "923a484f61165c88145f69735a4bd3ba4359e5169d25eff0ee23978cc79bd7c0"

      def install
        bin.install "sake"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/sake/releases/download/v0.11.0/sake_0.11.0_linux_amd64.tar.gz"
      sha256 "0f31f8d410bf98d4a480bf7d2e961d286fd4dd8d2a313978ca697a09f145d41c"

      def install
        bin.install "sake"
      end
    end
  end
end
