# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sake < Formula
  desc "sake is a CLI tool that enables you to run commands on servers via ssh"
  homepage "https://sakecli.com"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/sake/releases/download/v0.13.0/sake_0.13.0_darwin_amd64.tar.gz"
      sha256 "1c80e49087e5df770c59d3f5b686d51aff5c756def6d7f2ac152513b8715465d"

      def install
        bin.install "sake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alajmo/sake/releases/download/v0.13.0/sake_0.13.0_darwin_arm64.tar.gz"
      sha256 "e6ec96a03fd3e8f8aa3272812ab569d84689e0062aa2729ee5ccef9364f107d5"

      def install
        bin.install "sake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alajmo/sake/releases/download/v0.13.0/sake_0.13.0_linux_arm64.tar.gz"
      sha256 "abbfe8b011a6d83c44a046c28a2e8945a3146d3c3f34eabfdaf96a17f584ca1f"

      def install
        bin.install "sake"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/sake/releases/download/v0.13.0/sake_0.13.0_linux_amd64.tar.gz"
      sha256 "e9b19a2d1ce70f113dc265ac3797d3a592c4a5b60d5661615cdb3ea7b6a0ab4b"

      def install
        bin.install "sake"
      end
    end
  end
end
